newbies:
  starter-pack:
    oak-logs:
      ==: org.bukkit.inventory.ItemStack
      v: 2584
      type: OAK_LOG
      amount: 16
    steak:
      ==: org.bukkit.inventory.ItemStack
      v: 2584
      type: COOKED_BEEF
      amount: 16
    bytes:
      ==: org.bukkit.inventory.ItemStack
      v: 2584
      type: PAPER
      amount: 9
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Byte$"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Money!"}],"text":""}'
        custom-model-data: 8
        ItemFlags:
        - HIDE_ENCHANTS